# This is a legacy Dockerfile in terms of this project as is not compatible with AWS' Lambda
# ---- Stage BUILDER ----
FROM python:3.10-bookworm AS builder

# install uv
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /webcam-cloud

COPY ./pyproject.toml .

# install no-dev dependencies quickly with uv
RUN uv sync --extra endpoint --no-dev
    
# --- Stage PRODUCTION ----
FROM python:3.10-slim-bookworm AS production

# Set environment variables
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE

# Create app directory
WORKDIR /opt/ml

# Copy model and inference code
COPY . .

# use just installed dependencies from the builder stage
COPY --from=builder /webcam-cloud/.venv .venv

# Create folders required by SageMaker
RUN mkdir -p /opt/ml/model
RUN mkdir -p /opt/ml/input/data
RUN mkdir -p /opt/ml/output/data

# Define environment variables for inference
ENV SAGEMAKER_PROGRAM=modules/inference.py

# Set up environment variables for production
ENV PATH="/webcam-cloud/.venv/bin:$PATH"

# Define the entry point
ENTRYPOINT ["python", "modules/inference.py"]
