FROM python:3.10-bookworm AS builder

# install uv
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod -R 655 /install.sh && /install.sh && rm /install.sh

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /webcam-cloud

COPY ./pyproject.toml .

# install no-dev dependencies quickly with uv
RUN uv sync --extra wwwviewer --no-dev
    
# ---- Stage PRODUCTION ----
FROM python:3.10-slim-bookworm AS production

# Set environment variables
ENV PYTHONUNBUFFERED=1 \
    PORT=8050

# Expose the port
EXPOSE $PORT

# use and set ENV_STREAM_URL
ARG TF_VAR_region
ARG TF_VAR_db_img_stats_table
ARG TF_VAR_processed_bucket
ENV TF_VAR_region=$TF_VAR_region
ENV TF_VAR_db_img_stats_table=$TF_VAR_db_img_stats_table
ENV TF_VAR_processed_bucket=$TF_VAR_processed_bucket

WORKDIR /webcam-cloud
COPY . .

# use just installed dependencies from the builder stage
COPY --from=builder /webcam-cloud/.venv .venv

# Set up environment variables for production
ENV PATH="/webcam-cloud/.venv/bin:$PATH"

CMD ["gunicorn", "--bind", "0.0.0.0:8050", "dash_app.app:server"]